// frontend/src/components/navbar/index.tsx
"use client";

import { cn } from "@/lib/utils";
import { useScroll, useThrottle } from "ahooks";
import { NextLink } from "../next-link";
import Link from "next/link";
import { usePathname } from "next/navigation";
import React from "react";
import { PATHS, PATHS_MAP } from "@/lib/path"
import { ModeToggle } from "../mode-toggle"
import { Button } from "../ui/button";
import { IconBrandGithub } from "../icons/githubicon";
import { IconBrandBilibili } from "../icons/bilibiliicon";
import { UserCog } from "lucide-react";

export const Navbar = () => {
  const scroll = useScroll(() => document);
  const pathname = usePathname();
  const [previousScrollTop, setPreviousScrollTop] = React.useState(0);
  const throttledPreviousScrollTop = useThrottle(previousScrollTop, {
    wait: 500,
  });
  const [isHideHeader, setIsHideHeader] = React.useState(false);
  const throttledIsHideHeader = useThrottle(isHideHeader, { wait: 500 });

  React.useEffect(() => {
    const _top = scroll?.top ?? 0;

    if (_top - throttledPreviousScrollTop < 0) {
      // 向上滚动时，显示导航栏
      setIsHideHeader(false);
    } else {
      setIsHideHeader(true);
    }

    if (_top) {
      setPreviousScrollTop(_top);
    }
  }, [scroll?.top, throttledPreviousScrollTop]);
  return (
    <header
      className={cn(
        "w-full sticky top-0 backdrop-blur transition-all border-x-0  flex justify-center z-10",
        throttledPreviousScrollTop > 60 &&
        "bg-background/50 border-b border-border/50",
        {
          "-translate-y-20":
            throttledPreviousScrollTop > 300 ? throttledIsHideHeader : false,
        },
      )}>
      <div className="flex h-16 w-full items-center p-4 sm:p-8 md:max-w-screen-md 2xl:max-w-screen-xl">
        <NextLink
          href="/"
          className={cn("mr-4 hidden sm:flex")}
          aria-label="ExquisiteCore"
        >
          <span className="ml-2 text-base font-semibold text-primary">
            {"EC"}
          </span>
        </NextLink>
        <div className="mr-8 hidden h-16 flex-1 items-center justify-end text-base font-medium sm:flex">
          {navItems.map((el) => (
            <Link
              href={el.link}
              key={el.link}
              className={cn(
                "font-normal text-sm text-muted-foreground transition-colors px-4 py-2",
                "hover:font-semibold hover:text-primary ",
                pathname === el.link && "font-semibold text-primary",
              )}
            >
              {el.label}
            </Link>
          ))}
        </div>
        <div className="flex flex-1 items-center justify-end gap-2 sm:flex-none">

          <ModeToggle />

          <Link
            href="https://github.com/ExquisiteCore"
            target="_blank"
            title="https://github.com/ExquisiteCore"
            aria-label="https://github.com/ExquisiteCore"
          >
            <Button variant="outline" size={"icon"} aria-label="Github Icon">
              <IconBrandGithub className="text-base" />
            </Button>
          </Link>

          <Link
            href="https://space.bilibili.com/453875890"
            target="_blank"
            title="https://space.bilibili.com/453875890"
            aria-label="https://space.bilibili.com/453875890"
          >
            <Button variant="outline" size={"icon"} aria-label="BiliBili Icon">
              <IconBrandBilibili className="text-base" />
            </Button>
          </Link>

          <Link
            href="/signin"
            target="_blank"
            rel="nofollow"
            title="登录"
            aria-label="/signin"
          >
            <Button variant="outline" size={"icon"} aria-label="登录">
              <UserCog className="size-4" />
            </Button>
          </Link>
        </div>
      </div>
    </header>
  )
}

export const navItems: {
  label?: string;
  link: string;
  external?: boolean;
}[] = [
    {
      label: PATHS_MAP[PATHS.SITE_HOME],
      link: PATHS.SITE_HOME,
    },
    {
      label: PATHS_MAP[PATHS.SITE_BLOG],
      link: PATHS.SITE_BLOG,
    },
    {
      label: PATHS_MAP[PATHS.SITE_SNIPPET],
      link: PATHS.SITE_SNIPPET,
    },
    {
      label: PATHS_MAP[PATHS.SITE_ABOUT],
      link: PATHS.SITE_ABOUT,
    },
  ];

// frontend/components/navbar.vue
<template>
  <header :class="cn(
    'w-full sticky top-0 backdrop-blur transition-[background-color,border-width] border-x-0 flex justify-center z-10',
    scrollTop > 60 ? 'bg-background/50 border-b border-border/50' : ''
  )">
    <div class="flex h-16 w-full items-center p-4 sm:p-8 md:max-w-screen-md 2xl:max-w-screen-xl">

      <NuxtLink to="/" :class="cn('mr-4 hidden sm:flex')" aria-label=" EC">
        <p class="font-bold text-2xl">EC</p>
        <span class="ml-2 text-base font-semibold text-primary">
          精致的芯
        </span>
      </NuxtLink>
      <div class="mr-8 hidden h-16 flex-1 items-center justify-end text-base font-medium sm:flex">
        <NuxtLink v-for="el in navItems" :key="el.link" :to="el.link" :class="cn(
          'font-normal text-sm text-muted-foreground transition-colors px-4 py-2',
          'hover:font-semibold hover:text-primary',
          route.path === el.link && 'font-semibold text-primary'
        )">
          {{ el.label }}
        </NuxtLink>
      </div>
      <div class="flex flex-1 items-center justify-end gap-2 sm:flex-none">

        <NuxtLink to="https://github.com/exquisitecore/" target="_blank" title="https://github.com/exquisitecore/"
          aria-label="https://github.com/exquisitecore/">
          <Button variant="outline" size="icon">
            <GithubLogoIcon class="w-4 h-4" />
          </Button>
        </NuxtLink>

        <nuxt-link :to="isLoggedIn ? '/about' : '/signin'" rel="nofollow" title="登录" aria-label="登录">
          <Button variant="outline" class="w-9 h-9" aria-label="登录">
            <span v-if="!isLoggedIn">未登录</span>
            <span v-if="isLoggedIn">{{ username }}</span>
          </Button>
        </nuxt-link>
      </div>

    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { cn } from "@/lib/utils";
import { Button } from '@/components/ui/button'
import { GithubLogoIcon } from '@radix-icons/vue'

const scrollTop = ref(0)
const route = useRoute()

const userStore = useUserStore()
const isLoggedIn = ref(userStore.isLoggedIn)
const username = ref(userStore.getUsername())

// 监听 isLoggedIn 和 username 的变化
watch(() => userStore.isLoggedIn, (newValue) => {
  isLoggedIn.value = newValue
})

watch(() => userStore.getUsername(), (newValue) => {
  username.value = newValue
})

const navItems = [
  { label: '首页', link: '/' },
  { label: '博客', link: '/blog' },
  { label: '关于', link: '/about' },
  { label: '工具箱', link: '/toolbox' },
];

onMounted(() => {
  window.addEventListener('scroll', () => {
    scrollTop.value = window.scrollY
  })
})
</script>
