// frontend/components/MarkdownRenderer.tsx
'use client';

import { useEffect, useState } from 'react';
import { marked } from 'marked';
import '@/styles/markdown.scss';

interface MarkdownRendererProps {
  content: string;
}

export default function MarkdownRenderer({ content }: MarkdownRendererProps) {
  const [html, setHtml] = useState('');

  useEffect(() => {
    // 配置 marked
    marked.setOptions({
      gfm: true,
      breaks: true,
    });

    // 渲染 Markdown
    const rendered = marked(content);
    if (typeof rendered === 'string') {
      setHtml(rendered);
    } else {
      rendered.then(setHtml);
    }
  }, [content]);

  return (
    <div className="prose-indigo mx-auto prose rounded bg-white p-4 shadow-md">
      <div
        className="markdown-body"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}

// blog-web/src/components/solid/MarkdownRenderer.tsx
import { createSignal, onMount } from "solid-js";

import "@/styles/markdown.scss";

export default function MarkdownRenderer(props: { content: string }) {
  const [html, setHtml] = createSignal("");

  onMount(async () => {
    const wasm = await import("../../../md-wasm/pkg");
    await wasm.default(); // 初始化 WASM
    const rendered = wasm.render_markdown(props.content);
    setHtml(rendered);
  });

  return (
    <div class="prose prose-indigo mx-auto p-4 bg-white rounded shadow-md">
      <div class="markdown-body" innerHTML={html()} />
    </div>
  );
}
